apiVersion: v1
kind: PersistentVolume
metadata:
  name: jhub-pv
  labels:
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
# Enter here your Physical Volume definition. For example:
#  nfs:
#    path: NFS-exported full path
#    server: IP-address or FQDN of NFS-server
