apiVersion: v1
kind: Service
metadata:
  name: jhub-service
spec:
  selector:
    app: jhub-deployment
  ports:
    - name: hub
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: hub-api
      protocol: TCP
      port: 8081
      targetPort: 8081
